# Configure each UVC's parameters here

- uvc: some_uvc
  rst_is_negedge_sensitive: true
  clock_name: clock
  reset_name: nreset

  use_short_names: false
  agent_has_coverage: true
  gen_tdefs_pkg: false
  vif_in_config: false
  
  tr_props_vec:
    - field_name: data_to_send
      type: bit
      size: 8
      is_rand: true
      radix: HEX
    - field_name: data_received
      type: bit
      size: 8
      is_rand: false
      radix: hex
    - field_name: some_int_val
      type: int
      size: 2
      is_rand: false
      radix: dec
    - field_name: some_string_val
      type: string
      size: 1
      is_rand: false
      radix: hex
  
  if_sigs_vec:
    - field_name: ready_o
      type: logic
      size: 1
      is_output: true
    - field_name: valid_i
      type: logic
      size: 1
      is_output: false
    - field_name: data_o
      type: logic
      size: [8, 2]
      is_output: true
    - field_name: data_i
      type: logic
      size: 8
      is_output: false
  
  uvc_has_params: true
  use_env_params: false
  params_vec:
    - type: int
      name: PARAM1
      default_val: "100"
    - type: bit [7:0]
      name: PARAM2
      default_val: 8'hAB



- uvc: another_uvc
  rst_is_negedge_sensitive: true
  clock_name: clk
  reset_name: rst_n

  use_short_names: true
  agent_has_coverage: false
  gen_tdefs_pkg: true
  vif_in_config: true
  
  tr_props_vec:
    - field_name: random_data
      type: logic
      size: 16
      is_rand: true
      radix: hex
    - field_name: data_received
      type: bit
      size: 8
      is_rand: false
      radix: bin
  
  if_sigs_vec:
    - field_name: another_ready_o
      type: logic
      size: 1
      is_output: true
    - field_name: another_valid_i
      type: logic
      size: 1
      is_output: false
    - field_name: another_data_o
      type: logic
      size: 8
      is_output: true
    - field_name: another_data_i
      type: logic
      size: 8
      is_output: false
  
  class_names:
    agent: agt
    transaction: seq_item
    config: conf
  
  uvc_has_params: true
  use_env_params: true
  params_vec:
    - type: int
      name: PARAM1
      default_val: "100"
    - type: bit [7:0]
      name: PARAM2
      default_val: 8'hAB



- uvc: too_many_uvc
  rst_is_negedge_sensitive: true
  clock_name: clk
  reset_name: rst_n

  use_short_names: true
  agent_has_coverage: false
  gen_tdefs_pkg: false
  vif_in_config: true
  
  tr_props_vec:
    - field_name: random_data
      type: logic
      size: [3, 4]
      is_rand: true
      radix: hex
    - field_name: data_received
      type: bit
      size: 8
      is_rand: false
      radix: bin
  
  if_sigs_vec:
    - field_name: too_many_ready_o
      type: logic
      size: 1
      is_output: true
    - field_name: too_many_valid_i
      type: logic
      size: 1
      is_output: false
    - field_name: too_many_data_o
      type: logic
      size: 8
      is_output: true
    - field_name: too_many_data_i
      type: logic
      size: 8
      is_output: false
  
  uvc_has_params: false
  use_env_params: true
  params_vec:
    - type: int
      name: PARAM1
      default_val: "100"
    - type: bit [7:0]
      name: PARAM2
      default_val: 8'hAB
  